Repository secondmind-labs/trieste, pull requests merged in 2021-03, with the labels that each got.

#43 Reintroduce MES
  docs/refs.bib
  tests/unit/acquisition/test_function.py
  trieste/acquisition/__init__.py
  trieste/acquisition/function.py
Labels: bug

#194 Pareto set: Hypervolume
  tests/unit/test_pareto.py
  trieste/utils/pareto.py
Labels: feature:multi-objective

#177 add multi-output model wrapper
  tests/unit/models/test_model_interfaces.py
  trieste/models/__init__.py
  trieste/models/model_interfaces.py
Labels: feature:multi-objective

#186 allow custom acquisition optimizers
  docs/notebooks/expected_improvement.pct.py
  docs/notebooks/failure_ego.pct.py
  docs/notebooks/inequality_constraints.pct.py
  tests/unit/acquisition/test_function.py
  tests/unit/acquisition/test_optimizer.py
  tests/unit/acquisition/test_rule.py
  tests/unit/test_pareto.py
  tests/util/misc.py
  tests/util/model.py
  trieste/acquisition/__init__.py
  trieste/acquisition/optimizer.py
  trieste/acquisition/rule.py
Labels: enhancement

#199 remove `def _acquisition_function` pattern
  trieste/acquisition/function.py
Labels: enhancement

#152 add utility for mapping values in a mapping
  docs/notebooks/inequality_constraints.pct.py
  tests/unit/test_utils.py
  trieste/bayesian_optimizer.py
  trieste/utils/__init__.py
Labels: enhancement
