Repository secondmind-labs/trieste, pull requests merged in 2021-07, with the labels that each got.

#301 fixed Slack invitation links and made wording around it more precise
  CONTRIBUTING.md
  README.md
  docs/index.rst
Labels: bug

#257 Add qEHVI acquisition function
  docs/refs.bib
  tests/integration/test_multi_objective_bayesian_optimization.py
  tests/unit/acquisition/test_function.py
  tests/util/sampler.py
  trieste/acquisition/__init__.py
  trieste/acquisition/function.py
Labels: feature:multi-objective

#309 use tf.debugging for acquisition functions
  tests/thirdparty/__init__.py
  tests/thirdparty/test_tensorflow.py
  tests/unit/acquisition/test_function.py
  trieste/acquisition/function.py
Labels: code quality

#302 adding search space definitions for objectives
  docs/notebooks/batch_optimization.pct.py
  docs/notebooks/expected_improvement.pct.py
  docs/notebooks/failure_ego.pct.py
  docs/notebooks/multi_objective_ehvi.pct.py
  docs/notebooks/recovering_from_errors.pct.py
  docs/notebooks/thompson_sampling.pct.py
  tests/integration/test_bayesian_optimization.py
  tests/integration/test_multi_objective_bayesian_optimization.py
  tests/unit/acquisition/test_function.py
  tests/unit/acquisition/test_sampler.py
  tests/unit/objectives/__init__.py
  tests/unit/objectives/test_multi_objectives.py
  tests/unit/objectives/test_single_objectives.py
  tests/unit/objectives/test_utils.py
  trieste/__init__.py
  trieste/models/model_interfaces.py
  trieste/objectives/__init__.py
  trieste/objectives/multi_objectives.py
  trieste/objectives/single_objectives.py
  trieste/objectives/utils.py
  trieste/utils/__init__.py
Labels: enhancement
