Repository secondmind-labs/trieste, pull requests merged in 2021-04, with the labels that each got.

#97 fix model deepcopy
  common_build/format/constraints.txt
  common_build/types/constraints.txt
  docs/constraints.txt
  docs/notebooks/constraints.txt
  docs/notebooks/expected_improvement.pct.py
  docs/notebooks/failure_ego.pct.py
  docs/notebooks/inequality_constraints.pct.py
  docs/notebooks/thompson_sampling.pct.py
  tests/constraints.txt
  tests/requirements.txt
  tests/unit/models/test_model_interfaces.py
  trieste/bayesian_optimizer.py
  trieste/models/__init__.py
  trieste/models/model_interfaces.py
Labels: enhancement

#207 Pareto: Divide and conquer cells
  docs/refs.bib
  tests/unit/test_pareto.py
  trieste/utils/__init__.py
  trieste/utils/misc.py
  trieste/utils/pareto.py
Labels: feature:multi-objective

#217 add `get_hypercell_bounds` functionality
  tests/unit/test_pareto.py
  trieste/utils/pareto.py
Labels: feature:multi-objective

#202 Add analytic Ehvi acquisition function
  docs/refs.bib
  tests/unit/acquisition/test_function.py
  trieste/acquisition/__init__.py
  trieste/acquisition/function.py
  trieste/utils/pareto.py
Labels: feature:multi-objective

#226 Fixed inconsistensies with model sampling
  tests/unit/models/test_model_interfaces.py
  tests/util/model.py
  tests/util/test_model.py
  trieste/acquisition/rule.py
  trieste/models/model_interfaces.py
Labels: bug

#231 Fix docs build and reduce warnings
  .github/workflows/quality-checks.yaml
  common_build/format/constraints.txt
  common_build/taskipy/constraints.txt
  docs/Makefile
  docs/README.md
  docs/conf.py
  docs/constraints.txt
  docs/make.bat
  docs/notebooks/constraints.txt
  docs/refs.bib
  docs/tutorials.rst
  tests/constraints.txt
  tox.ini
  trieste/acquisition/function.py
  trieste/acquisition/sampler.py
  trieste/data.py
  trieste/utils/objectives.py
  trieste/utils/pareto.py
Labels: bug, documentation

#190 add multi-objective toy function
  docs/refs.bib
  tests/unit/utils/test_objectives.py
  trieste/utils/multi_objectives.py
Labels: feature:multi-objective
